package com.hafizuddin.nomadwealth

import android.os.Bundle
import androidx.activity.ComponentActivity
import androidx.activity.compose.setContent
import androidx.activity.enableEdgeToEdge
import androidx.compose.animation.AnimatedContent
import androidx.compose.foundation.background
import androidx.compose.foundation.layout.*
import androidx.compose.foundation.lazy.LazyColumn
import androidx.compose.foundation.lazy.items
import androidx.compose.foundation.rememberScrollState
import androidx.compose.foundation.shape.CircleShape
import androidx.compose.foundation.shape.RoundedCornerShape
import androidx.compose.foundation.verticalScroll
import androidx.compose.material.icons.Icons
import androidx.compose.material.icons.filled.*
import androidx.compose.material3.*
import androidx.compose.runtime.*
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.graphics.Brush
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.text.font.FontWeight
import androidx.compose.ui.text.input.PasswordVisualTransformation
import androidx.compose.ui.text.style.TextAlign
import androidx.compose.ui.unit.dp
import androidx.compose.ui.unit.sp
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.launch
import kotlinx.coroutines.withContext
import org.json.JSONObject
import java.net.HttpURLConnection
import java.net.URL
import java.text.NumberFormat
import java.util.*

data class Account(val name:String,val currency:String,val balance:Double)
data class Tx(val title:String,val category:String,val amount:Double,val income:Boolean,val date:String)
data class Loan(val name:String,val principal:Double,val remaining:Double,val payment:Double,val currency:String)
data class Session(val name:String,val email:String,val token:String)
enum class Route{LANDING,LOGIN,SIGNUP,APP}
enum class Tab(val label:String){DASHBOARD("Dashboard"),ACCOUNTS("Accounts"),TRANSACTIONS("Transactions"),LOANS("Loans"),PROFILE("Profile")}

class MainActivity:ComponentActivity(){override fun onCreate(savedInstanceState:Bundle?){super.onCreate(savedInstanceState);enableEdgeToEdge();setContent{NomadTheme{NomadApp()}}}}

private val dark=darkColorScheme(primary=Color(0xFF18C6B5),secondary=Color(0xFF56A8FF),background=Color(0xFF07151D),surface=Color(0xFF0E202A),error=Color(0xFFFF5C67))
private val light=lightColorScheme(primary=Color(0xFF007E73),secondary=Color(0xFF1265A8),background=Color(0xFFF4F7F8),surface=Color.White)
@Composable fun NomadTheme(content:@Composable()->Unit){MaterialTheme(colorScheme=if(androidx.compose.foundation.isSystemInDarkTheme()) dark else light,content=content)}

@Composable fun NomadApp(){var route by remember{mutableStateOf(Route.LANDING)};var session by remember{mutableStateOf<Session?>(null)};AnimatedContent(route,label="route"){r->when(r){Route.LANDING->Landing({route=Route.LOGIN},{route=Route.SIGNUP});Route.LOGIN->Auth(false,{route=Route.LANDING}){session=it;route=Route.APP};Route.SIGNUP->Auth(true,{route=Route.LANDING}){route=Route.LOGIN};Route.APP->MainApp(session?:Session("Nomad","","")){session=null;route=Route.LANDING}}}}

@Composable fun Landing(login:()->Unit,signup:()->Unit){Column(Modifier.fillMaxSize().background(Brush.verticalGradient(listOf(Color(0xFF06131C),Color(0xFF06323A),Color(0xFF06131C)))).statusBarsPadding().verticalScroll(rememberScrollState()).padding(20.dp),horizontalAlignment=Alignment.CenterHorizontally){Row(Modifier.fillMaxWidth(),verticalAlignment=Alignment.CenterVertically){Icon(Icons.Default.Explore,null,tint=Color(0xFF18C6B5),modifier=Modifier.size(42.dp));Spacer(Modifier.width(10.dp));Column{Text("Nomad Wealth",color=Color.White,fontWeight=FontWeight.Bold,fontSize=20.sp);Text("Your money. Anywhere.",color=Color.White.copy(.65f),fontSize=12.sp)};Spacer(Modifier.weight(1f));TextButton(onClick=login){Text("Log in",color=Color.White)}};Spacer(Modifier.height(34.dp));Surface(color=Color(0xFF18C6B5).copy(.14f),shape=CircleShape){Text("PERSONAL FINANCE ACROSS COUNTRIES",color=Color(0xFF4FE6D8),fontSize=11.sp,fontWeight=FontWeight.Bold,modifier=Modifier.padding(horizontal=14.dp,vertical=8.dp))};Spacer(Modifier.height(22.dp));Icon(Icons.Default.Explore,null,tint=Color(0xFF18C6B5),modifier=Modifier.size(88.dp));Text("Understand your money,\nwherever life takes you.",color=Color.White,fontSize=38.sp,fontWeight=FontWeight.Bold,lineHeight=43.sp,textAlign=TextAlign.Center);Spacer(Modifier.height(14.dp));Text("Track accounts, income, expenses, budgets, loans and currencies from one native Android app.",color=Color.White.copy(.72f),textAlign=TextAlign.Center,lineHeight=24.sp);Spacer(Modifier.height(24.dp));Feature(Icons.Default.Public,"Multi-currency accounts","Manage money across countries and currencies.");Feature(Icons.Default.SwapHoriz,"Simple money tracking","Record Money In and Money Out clearly.");Feature(Icons.Default.AccountBalance,"Loans and installments","Track principal, payments and remaining debt.");Spacer(Modifier.height(18.dp));Preview();Spacer(Modifier.height(22.dp));Button(onClick=signup,modifier=Modifier.fillMaxWidth().height(54.dp),shape=RoundedCornerShape(16.dp)){Icon(Icons.Default.PersonAdd,null);Spacer(Modifier.width(8.dp));Text("Create free account",fontWeight=FontWeight.Bold)};Spacer(Modifier.height(10.dp));OutlinedButton(onClick=login,modifier=Modifier.fillMaxWidth().height(54.dp),shape=RoundedCornerShape(16.dp)){Text("Log in",color=Color.White)};Spacer(Modifier.height(22.dp));Text("Nomad Wealth · Developed by Hafizuddin",color=Color.White.copy(.45f),fontSize=12.sp)}}
@Composable fun Feature(icon:androidx.compose.ui.graphics.vector.ImageVector,title:String,text:String){Surface(color=Color.White.copy(.06f),shape=RoundedCornerShape(18.dp),modifier=Modifier.fillMaxWidth().padding(vertical=5.dp)){Row(Modifier.padding(16.dp),verticalAlignment=Alignment.CenterVertically){Icon(icon,null,tint=Color(0xFF4FE6D8),modifier=Modifier.size(28.dp));Spacer(Modifier.width(14.dp));Column{Text(title,color=Color.White,fontWeight=FontWeight.Bold);Text(text,color=Color.White.copy(.65f),fontSize=13.sp)}}}}
@Composable fun Preview(){Surface(color=Color.White.copy(.06f),shape=RoundedCornerShape(24.dp),modifier=Modifier.fillMaxWidth()){Column(Modifier.padding(18.dp)){Text("FINANCIAL PREVIEW",color=Color(0xFF4FE6D8),fontSize=11.sp,fontWeight=FontWeight.Bold);Text("Everything important in one view",color=Color.White,fontWeight=FontWeight.Bold,fontSize=19.sp);Spacer(Modifier.height(14.dp));Surface(color=Color(0xFF117C7A),shape=RoundedCornerShape(18.dp)){Column(Modifier.fillMaxWidth().padding(18.dp)){Text("Remaining balance",color=Color.White.copy(.7f),fontSize=12.sp);Text("€2,070.00",color=Color.White,fontSize=31.sp,fontWeight=FontWeight.Bold);Text("Income minus expenses",color=Color(0xFF6FF4E7),fontSize=12.sp)}}}}}

class AuthApi{private val url=BuildConfig.SUPABASE_URL.trimEnd('/');private val key=BuildConfig.SUPABASE_ANON_KEY;fun configured()=url.startsWith("https://")&&key.isNotBlank();fun login(email:String,password:String):Result<Session>=runCatching{check(configured()){"Supabase is not configured. Add GitHub repository secrets."};val j=post("/auth/v1/token?grant_type=password",JSONObject().put("email",email).put("password",password));val token=j.optString("access_token");if(token.isBlank())error(j.optString("msg",j.optString("error_description",j.optString("error","Authentication failed."))));val u=j.optJSONObject("user");val n=u?.optJSONObject("user_metadata")?.optString("name")?.takeIf{it.isNotBlank()}?:email.substringBefore("@").replaceFirstChar{it.uppercase()};Session(n,email,token)};fun signup(name:String,email:String,password:String):Result<String>=runCatching{check(configured()){"Supabase is not configured. Add GitHub repository secrets."};val j=post("/auth/v1/signup",JSONObject().put("email",email).put("password",password).put("data",JSONObject().put("name",name)));if(j.has("error")||j.has("msg"))error(j.optString("msg",j.optString("error","Registration failed.")));"Account created. Confirm your email, then log in."};private fun post(path:String,body:JSONObject):JSONObject{val c=URL("$url$path").openConnection() as HttpURLConnection;return try{c.requestMethod="POST";c.connectTimeout=20000;c.readTimeout=20000;c.doOutput=true;c.setRequestProperty("Content-Type","application/json");c.setRequestProperty("apikey",key);c.setRequestProperty("Authorization","Bearer $key");c.outputStream.bufferedWriter().use{it.write(body.toString())};val s=if(c.responseCode in 200..299)c.inputStream else c.errorStream;JSONObject(s.bufferedReader().use{it.readText()}.ifBlank{"{}"})}finally{c.disconnect()}}}

@Composable fun Auth(signup:Boolean,back:()->Unit,success:(Session)->Unit){val api=remember{AuthApi()};val scope=rememberCoroutineScope();var name by remember{mutableStateOf("")};var email by remember{mutableStateOf("")};var pass by remember{mutableStateOf("")};var confirm by remember{mutableStateOf("")};var loading by remember{mutableStateOf(false)};var msg by remember{mutableStateOf("")};Scaffold(topBar={TopAppBar(title={Text(if(signup)"Create account" else "Log in")},navigationIcon={IconButton(onClick=back){Icon(Icons.Default.ArrowBack,"Back")}})}){pad->Column(Modifier.fillMaxSize().padding(pad).padding(22.dp).verticalScroll(rememberScrollState()),horizontalAlignment=Alignment.CenterHorizontally){Icon(Icons.Default.Explore,null,tint=MaterialTheme.colorScheme.primary,modifier=Modifier.size(70.dp));Text("Nomad Wealth",fontSize=26.sp,fontWeight=FontWeight.Bold);Spacer(Modifier.height(24.dp));if(signup){OutlinedTextField(name,{name=it},label={Text("Your name")},modifier=Modifier.fillMaxWidth());Spacer(Modifier.height(10.dp))};OutlinedTextField(email,{email=it},label={Text("Email")},modifier=Modifier.fillMaxWidth());Spacer(Modifier.height(10.dp));OutlinedTextField(pass,{pass=it},label={Text("Password")},visualTransformation=PasswordVisualTransformation(),modifier=Modifier.fillMaxWidth());if(signup){Spacer(Modifier.height(10.dp));OutlinedTextField(confirm,{confirm=it},label={Text("Confirm password")},visualTransformation=PasswordVisualTransformation(),modifier=Modifier.fillMaxWidth())};if(msg.isNotBlank()){Spacer(Modifier.height(12.dp));Text(msg,color=if(msg.startsWith("Account created"))MaterialTheme.colorScheme.primary else MaterialTheme.colorScheme.error)};Spacer(Modifier.height(18.dp));Button(onClick={msg="";if(!email.contains("@")||pass.length<6){msg="Enter a valid email and a password with at least 6 characters.";return@Button};if(signup&&(name.isBlank()||pass!=confirm)){msg=if(name.isBlank())"Enter your name." else "Passwords do not match.";return@Button};loading=true;scope.launch{if(signup){val r=withContext(Dispatchers.IO){api.signup(name.trim(),email.trim(),pass)};loading=false;r.onSuccess{msg=it}.onFailure{msg=it.message?:"Registration failed."}}else{val r=withContext(Dispatchers.IO){api.login(email.trim(),pass)};loading=false;r.onSuccess(success).onFailure{msg=it.message?:"Login failed."}}}},enabled=!loading,modifier=Modifier.fillMaxWidth().height(54.dp),shape=RoundedCornerShape(16.dp)){if(loading)CircularProgressIndicator(Modifier.size(22.dp),strokeWidth=2.dp)else Text(if(signup)"Create account" else "Log in",fontWeight=FontWeight.Bold)};if(!api.configured()){Spacer(Modifier.height(18.dp));Text("Authentication needs GitHub Secrets. The demo interface still builds.",color=MaterialTheme.colorScheme.onSurfaceVariant,fontSize=12.sp,textAlign=TextAlign.Center)}}}}

@Composable fun MainApp(session:Session,logout:()->Unit){var tab by remember{mutableStateOf(Tab.DASHBOARD)};val accounts=remember{mutableStateListOf(Account("Main account","EUR",1450.0),Account("Freelance wallet","USD",620.0))};val txs=remember{mutableStateListOf(Tx("Freelance payment","Income",600.0,true,"Today"),Tx("Rent","Housing",400.0,false,"Today"),Tx("Groceries","Food",48.0,false,"Yesterday"))};val loans=remember{mutableStateListOf(Loan("Education loan",5000.0,3200.0,180.0,"EUR"))};Scaffold(bottomBar={NavigationBar{Tab.entries.forEach{i->NavigationBarItem(selected=tab==i,onClick={tab=i},icon={Icon(when(i){Tab.DASHBOARD->Icons.Default.Home;Tab.ACCOUNTS->Icons.Default.CreditCard;Tab.TRANSACTIONS->Icons.Default.SwapHoriz;Tab.LOANS->Icons.Default.AccountBalance;Tab.PROFILE->Icons.Default.Person},i.label)},label={Text(i.label,fontSize=10.sp)})}}}){p->Box(Modifier.fillMaxSize().padding(p)){when(tab){Tab.DASHBOARD->Dashboard(session.name,accounts,txs);Tab.ACCOUNTS->Accounts(accounts);Tab.TRANSACTIONS->Transactions(txs);Tab.LOANS->Loans(loans);Tab.PROFILE->Profile(session,accounts.size,txs.size,loans.size,logout)}}}}

@Composable fun Dashboard(name:String,accounts:List<Account>,txs:List<Tx>){val income=txs.filter{it.income}.sumOf{it.amount};val expense=txs.filter{!it.income}.sumOf{it.amount};LazyColumn(Modifier.fillMaxSize().padding(horizontal=16.dp),contentPadding=PaddingValues(top=18.dp,bottom=24.dp),verticalArrangement=Arrangement.spacedBy(14.dp)){item{Text("Overview",fontSize=34.sp,fontWeight=FontWeight.Bold);Spacer(Modifier.height(10.dp));Surface(color=MaterialTheme.colorScheme.primary.copy(.12f),shape=RoundedCornerShape(22.dp)){Row(Modifier.fillMaxWidth().padding(18.dp),verticalAlignment=Alignment.CenterVertically){Surface(color=MaterialTheme.colorScheme.primary,shape=CircleShape){Text(name.take(1).uppercase(),color=MaterialTheme.colorScheme.onPrimary,fontSize=24.sp,fontWeight=FontWeight.Bold,modifier=Modifier.padding(horizontal=18.dp,vertical=12.dp))};Spacer(Modifier.width(14.dp));Column{Text(greeting().uppercase(),color=MaterialTheme.colorScheme.primary,fontSize=11.sp,fontWeight=FontWeight.Bold);Text(name,fontSize=25.sp,fontWeight=FontWeight.Bold);Text("Here is your financial overview",color=MaterialTheme.colorScheme.onSurfaceVariant)}}}};item{Row(horizontalArrangement=Arrangement.spacedBy(10.dp)){Metric("Income",income,Color(0xFF25CF69),Modifier.weight(1f));Metric("Expenses",expense,Color(0xFFFF4D59),Modifier.weight(1f))}};item{Metric("Remaining this month",income-expense,MaterialTheme.colorScheme.secondary,Modifier.fillMaxWidth())};item{Text("Financial accounts",fontSize=22.sp,fontWeight=FontWeight.Bold)};items(accounts){AccountRow(it)};item{Text("Recent transactions",fontSize=22.sp,fontWeight=FontWeight.Bold)};items(txs){TxRow(it)}}}
fun greeting():String{val h=Calendar.getInstance().get(Calendar.HOUR_OF_DAY);return if(h<12)"Good morning" else if(h<18)"Good afternoon" else "Good evening"}
@Composable fun Metric(t:String,v:Double,c:Color,m:Modifier){Surface(modifier=m,shape=RoundedCornerShape(18.dp),tonalElevation=2.dp){Column(Modifier.padding(18.dp)){Text(t,color=MaterialTheme.colorScheme.onSurfaceVariant,fontSize=13.sp);Text(money(v),color=c,fontSize=25.sp,fontWeight=FontWeight.Bold)}}}
@Composable fun Accounts(a:MutableList<Account>){var add by remember{mutableStateOf(false)};Header("Accounts","Manage money across currencies"){FilledTonalButton(onClick={add=true}){Icon(Icons.Default.Add,null);Text(" Add")}};LazyColumn(Modifier.fillMaxSize().padding(top=90.dp,start=16.dp,end=16.dp),verticalArrangement=Arrangement.spacedBy(12.dp)){items(a){AccountRow(it)}};if(add)AddDialog("Add account","Account name",{add=false}){a.add(Account(it,"EUR",0.0));add=false}}
@Composable fun Transactions(t:MutableList<Tx>){var add by remember{mutableStateOf(false)};Header("Transactions","Your Money In and Money Out"){FilledTonalButton(onClick={add=true}){Icon(Icons.Default.Add,null);Text(" Add")}};LazyColumn(Modifier.fillMaxSize().padding(top=90.dp,start=16.dp,end=16.dp),verticalArrangement=Arrangement.spacedBy(10.dp)){items(t){TxRow(it)}};if(add)AddDialog("Add transaction","Transaction title",{add=false}){t.add(0,Tx(it,"Other",25.0,false,"Today"));add=false}}
@Composable fun Loans(l:MutableList<Loan>){var add by remember{mutableStateOf(false)};Header("Loans","Track installments and remaining debt"){FilledTonalButton(onClick={add=true}){Icon(Icons.Default.Add,null);Text(" Add")}};LazyColumn(Modifier.fillMaxSize().padding(top=90.dp,start=16.dp,end=16.dp),verticalArrangement=Arrangement.spacedBy(12.dp)){items(l){x->Surface(shape=RoundedCornerShape(18.dp),tonalElevation=2.dp){Column(Modifier.fillMaxWidth().padding(18.dp)){Text(x.name,fontWeight=FontWeight.Bold,fontSize=18.sp);Text("Remaining: ${x.currency} ${x.remaining}",color=MaterialTheme.colorScheme.error);Text("Monthly payment: ${x.currency} ${x.payment}",color=MaterialTheme.colorScheme.onSurfaceVariant);Spacer(Modifier.height(10.dp));LinearProgressIndicator(progress={((x.principal-x.remaining)/x.principal).toFloat().coerceIn(0f,1f)},modifier=Modifier.fillMaxWidth())}}}};if(add)AddDialog("Add loan","Loan name",{add=false}){l.add(Loan(it,1000.0,1000.0,100.0,"EUR"));add=false}}
@Composable fun Profile(s:Session,ac:Int,tc:Int,lc:Int,logout:()->Unit){Column(Modifier.fillMaxSize().verticalScroll(rememberScrollState()).padding(18.dp),horizontalAlignment=Alignment.CenterHorizontally){Text("Profile",modifier=Modifier.fillMaxWidth(),fontSize=34.sp,fontWeight=FontWeight.Bold);Spacer(Modifier.height(18.dp));Surface(color=MaterialTheme.colorScheme.primary.copy(.12f),shape=RoundedCornerShape(24.dp),modifier=Modifier.fillMaxWidth()){Column(Modifier.padding(26.dp),horizontalAlignment=Alignment.CenterHorizontally){Surface(color=MaterialTheme.colorScheme.primary,shape=CircleShape){Text(s.name.take(2).uppercase(),color=MaterialTheme.colorScheme.onPrimary,fontSize=30.sp,fontWeight=FontWeight.Bold,modifier=Modifier.padding(22.dp))};Spacer(Modifier.height(12.dp));Text(s.name,fontSize=25.sp,fontWeight=FontWeight.Bold);Text(s.email.ifBlank{"Demo profile"},color=MaterialTheme.colorScheme.onSurfaceVariant)}};Spacer(Modifier.height(14.dp));Row(horizontalArrangement=Arrangement.spacedBy(8.dp)){Stat("$ac","Accounts",Modifier.weight(1f));Stat("$tc","Entries",Modifier.weight(1f));Stat("$lc","Loans",Modifier.weight(1f))};Spacer(Modifier.height(18.dp));Surface(shape=RoundedCornerShape(20.dp),tonalElevation=2.dp,modifier=Modifier.fillMaxWidth()){Column(Modifier.padding(18.dp)){Text("Account security",fontSize=19.sp,fontWeight=FontWeight.Bold);Text("Supabase email authentication",color=MaterialTheme.colorScheme.onSurfaceVariant);Text("HTTPS-only communication",color=MaterialTheme.colorScheme.onSurfaceVariant);Text("No service-role key included",color=MaterialTheme.colorScheme.onSurfaceVariant)}};Spacer(Modifier.height(18.dp));OutlinedButton(onClick=logout,modifier=Modifier.fillMaxWidth().height(52.dp)){Icon(Icons.Default.Logout,null);Spacer(Modifier.width(8.dp));Text("Log out")}}}
@Composable fun Header(t:String,s:String,a:@Composable()->Unit){Row(Modifier.fillMaxWidth().padding(horizontal=16.dp,vertical=18.dp),verticalAlignment=Alignment.CenterVertically){Column{Text(t,fontSize=31.sp,fontWeight=FontWeight.Bold);Text(s,color=MaterialTheme.colorScheme.onSurfaceVariant,fontSize=13.sp)};Spacer(Modifier.weight(1f));a()}}
@Composable fun AccountRow(a:Account){Surface(shape=RoundedCornerShape(18.dp),tonalElevation=2.dp){Row(Modifier.fillMaxWidth().padding(18.dp),verticalAlignment=Alignment.CenterVertically){Icon(Icons.Default.CreditCard,null,tint=MaterialTheme.colorScheme.primary);Spacer(Modifier.width(12.dp));Column{Text(a.name,fontWeight=FontWeight.Bold);Text(a.currency,color=MaterialTheme.colorScheme.onSurfaceVariant,fontSize=12.sp)};Spacer(Modifier.weight(1f));Text("${a.currency} ${"%.2f".format(a.balance)}",fontWeight=FontWeight.Bold)}}}
@Composable fun TxRow(t:Tx){Surface(shape=RoundedCornerShape(16.dp),tonalElevation=1.dp){Row(Modifier.fillMaxWidth().padding(15.dp),verticalAlignment=Alignment.CenterVertically){Icon(if(t.income)Icons.Default.ArrowCircleDown else Icons.Default.ArrowCircleUp,null,tint=if(t.income)Color(0xFF25CF69) else Color(0xFFFF4D59));Spacer(Modifier.width(12.dp));Column{Text(t.title,fontWeight=FontWeight.Bold);Text("${t.category} · ${t.date}",color=MaterialTheme.colorScheme.onSurfaceVariant,fontSize=12.sp)};Spacer(Modifier.weight(1f));Text("${if(t.income)"+" else "-"}${money(t.amount)}",color=if(t.income)Color(0xFF25CF69) else Color(0xFFFF4D59),fontWeight=FontWeight.Bold)}}}
@Composable fun Stat(v:String,l:String,m:Modifier){Surface(modifier=m,shape=RoundedCornerShape(16.dp),tonalElevation=2.dp){Column(Modifier.padding(vertical=15.dp),horizontalAlignment=Alignment.CenterHorizontally){Text(v,fontSize=21.sp,fontWeight=FontWeight.Bold);Text(l,fontSize=11.sp,color=MaterialTheme.colorScheme.onSurfaceVariant)}}}
@Composable fun AddDialog(t:String,f:String,d:()->Unit,add:(String)->Unit){var v by remember{mutableStateOf("")};AlertDialog(onDismissRequest=d,title={Text(t)},text={OutlinedTextField(v,{v=it},label={Text(f)})},confirmButton={TextButton(onClick={if(v.isNotBlank())add(v.trim())}){Text("Add")}},dismissButton={TextButton(onClick=d){Text("Cancel")}})}
fun money(v:Double)=NumberFormat.getCurrencyInstance(Locale.GERMANY).format(v)
